export enum ROUTES {
  AUTH = "/auth",
  LOGIN = "/auth/login",
  SIGNUP = "/auth/signup",
  HOME = "/",
  CONTACTS = "/contacts",
  FRIENDS = "/contacts/all-friends",
  GROUPS = "/contacts/groups",
  FRIEND_REQUESTS = "/contacts/friends-request",
  CHATS = "/chats",
  CHAT = "/chat/:id",
  TODOS = "/todos",
  PROFILE = "/profile",
  SETTINGS = "/settings",
  SEARCH = "/search",
}
