export enum QueryKey {
  USER = "user",
  FRIEND_SEARCH = "FRIEND_SEARCH",
  FRIEND_REQUEST = "FRIEND_REQUEST",
  SEND_FIEND_REQUEST = "SEND_FIEND_REQUEST",
  ALL_FRIENDS = "ALL_FRIENDS",
  SEND_MESSAGE = "SEND_MESSAGE",
  GET_MESSAGES = "GET_MESSAGES",
  GET_CONVERSATION = "GET_CONVERSATION",
  GET_CONVERSATIONS = "GET_CONVERSATIONS",
}
